version: "3"

services:
  db:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    depends_on:
      - db

  php:
    build:
      context: .boing/docker/php
    volumes:
      - .:/srv

  web:
    depends_on:
      - php
    build:
      context: .boing/docker/nginx/symfony
    volumes:
      - ./public:/srv/public

volumes:
  db_data:
